name: deb package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: inspect debhelper
      run: apt-cache showpkg debhelper
    - name: removing gcc10
      run: sudo apt remove libgcc-10-dev
    - name: setting the dependencies up
      run: sudo apt install -t bionic-backports libfontconfig1-dev zlib1g-dev libjsoncpp-dev libgtksourceviewmm-3.0-dev libgtkmm-3.0-dev libtinyxml2-dev cmake debhelper=13.6ubuntu1~bpo18.04.1 dpkg-dev
    - name: running debhelper
      run: dpkg-buildpackage -b -uc 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-deb"
        prerelease: true
        title: "Ubuntu 18.04 package for development version"
        files: ../notekit_0.2_amd64.deb

